export const POSTGRESQL_TYPES: Record<string, readonly string[]> = {
  'Integer': ['smallint', 'int2', 'integer', 'int', 'int4', 'bigint', 'int8'],
  'Auto-increment': ['serial', 'bigserial'],
  'Exact Decimal': ['decimal', 'numeric'],
  'Float': ['real', 'float4', 'double precision', 'float8', 'float'],
  'Currency': ['money'],
  'Character': ['char', 'varchar', 'text'],
  'Binary': ['bit', 'bytea', 'varbit'],
  'Boolean': ['boolean', 'bool'],
  'Date & Time': ['date', 'time', 'timestamp', 'timestamptz', 'interval'],
  'UUID / GUID': ['uuid'],
  'JSON': ['json', 'jsonb'],
  'XML': ['xml'],
  'Enum': ['enum'],
  'Network': ['inet', 'cidr', 'macaddr', 'macaddr8'],
  'Geometric / Spatial': ['point', 'line', 'lseg', 'polygon', 'circle', 'box'],
  'Range': ['int4range', 'int8range', 'numrange', 'tsrange', 'tstzrange', 'daterange'],
  'Arrays': ['array'],
  'Full-text search': ['tsvector', 'tsquery'],
  'Row identifiers': ['ctid'],
  'Special / misc': ['pg_lsn', 'oid'],
} as const;
