export const SQLSERVER_TYPES: Record<string, readonly string[]> = {
  'Integer': ['TINYINT', 'SMALLINT', 'INT', 'BIGINT'],
  'Exact Decimal': ['DECIMAL', 'NUMERIC'],
  'Float': ['REAL', 'FLOAT'],
  'Currency': ['MONEY', 'SMALLMONEY'],
  'Character': ['CHAR', 'VARCHAR', 'VARCHAR(MAX)'],
  'Unicode': ['NCHAR', 'NVARCHAR', 'NVARCHAR(MAX)'],
  'Binary': ['BINARY', 'VARBINARY', 'VARBINARY(MAX)', 'BIT'],
  'Boolean': ['BIT'],
  'Date & Time': ['DATE', 'TIME', 'DATETIME2', 'DATETIMEOFFSET', 'DATETIME', 'SMALLDATETIME'],
  'UUID / GUID': ['UNIQUEIDENTIFIER'],
  'XML': ['XML'],
  'Geometric / Spatial': ['GEOMETRY', 'GEOGRAPHY'],
  'Special / misc': ['SQL_VARIANT', 'HIERARCHYID', 'CURSOR', 'TABLE'],
} as const;
